### PR TITLE
Added otu_ids to the tax_data when parsing phyloseq objects.

### PR DESCRIPTION
**Pull request by grabear**
This is super helpful whenever you need to filter the otu_table and the tax_data at the same time.

### CODE REVIEW

**Comment by grabear** [comment]
@zachary-foster Hey I just wanted you to know that I could have merged this on my own if I wanted to.  You may want to change my permissions so that my PR's _require_ a review.

**Comment by zachary-foster** [comment]
Hi @grabear, thanks!

Did you intend to close the issue?

**Comment by grabear** [comment]
Yes!  I might open it back up, but there may be something funny going on.

**Comment by grabear** [comment]
I starting using this PR on my local machine and I thought it was doing something to the filter functions, but it turns out I was mistaken.  It was something that I was doing wrong.  So if you think this will be a good PR then feel free to merge it! @zachary-foster

**Comment by zachary-foster** [comment]
Looks good. Thanks @grabear !

**Pull request merged**
